var todo = {};


var json = {
    "To-Do 1": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Meet with Andy re: Data Project",
        "dtDue": "2/18/2013",
        "assignedTo": "James Makowski",
        "priority": "27",
        "sendEmail": "Yes",
        "content": "Talk to Andy about incorporating ethnicity information into data tracking projects.",
    },
    "To-Do 2": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Add Search Feature to Data Project",
        "dtDue": "2/18/2013",
        "assignedTo": "Garrett Moore",
        "priority": "33",
        "sendEmail": "No",
        "content": "Implement Search feature to find guest by first name, last name and email address.",
    },
    "To-Do 3": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Finalize Budget",
        "dtDue": "2/18/2013",
        "assignedTo": "James Makowski",
        "priority": "37",
        "sendEmail": "Yes",
        "content": "Line-by-line review of annual budget. Submit to manager when complete",
    },
    "To-Do 4": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Add Guest System to Tour Database",
        "dtDue": "2/19/2013",
        "assignedTo": "Garrett Moore",
        "priority": "44",
        "sendEmail": "Yes",
        "content": "Implement guest system for Tour Database.",
    },
    "To-Do 5": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Discuss Bussing Staff Requirements",
        "dtDue": "2/19/2013",
        "assignedTo": "Sarah Slegona",
        "priority": "18",
        "sendEmail": "Yes",
        "content": "Discuss bussing quantity and drivers needed with Jim.",
    },
    "To-Do 6": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Update Events Spreadsheet",
        "dtDue": "2/19/2013",
        "assignedTo": "Sarah Slegona",
        "priority": "2",
        "sendEmail": "Yes",
        "content": "Update spreadsheet with newly-generated events.",
    },
    "To-Do 7": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Contact Bussing Vendor for Event",
        "dtDue": "2/18/2013",
        "assignedTo": "Sarah Slegona",
        "priority": "96",
        "sendEmail": "Yes",
        "content": "Talk to Bussing Vendor to get invoice for previous event.",
    },
    "To-Do 8": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Contact Catering Vendor for Event",
        "dtDue": "2/18/2013",
        "assignedTo": "Sarah Slegona",
        "priority": "96",
        "sendEmail": "Yes",
        "content": "Get deposit invoice from catering company.",
    },
    "To-Do 9": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Verify Radio Count from Vendor",
        "dtDue": "2/20/2013",
        "assignedTo": "James Makowski",
        "priority": "88",
        "sendEmail": "Yes",
        "content": "Verify 42 radios from Central Communcations.",
    },
    "To-Do 10": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Hold Lunch Meeting",
        "dtDue": "2/21/2013",
        "assignedTo": "James Makowski",
        "priority": "99",
        "sendEmail": "Yes",
        "content": "Hold Lunch Meeting with Security, IMT, Runners, I&D, etc.",
    },
    "To-Do 11": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Prepare Table Top Signage",
        "dtDue": "2/22/2013",
        "assignedTo": "Sarah Slegona",
        "priority": "88",
        "sendEmail": "Yes",
        "content": "Verify that all signs were returned and print/prepare new ones as needed.",
    },
    "To-Do 12": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Prepare Paint Stick Signage",
        "dtDue": "2/22/2013",
        "assignedTo": "Sarah Slegona",
        "priority": "88",
        "sendEmail": "Yes",
        "content": "Verify all signs were returned and print/prepare new ones as needed.",
    },
    "To-Do 13": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Make Office Depot Trip",
        "dtDue": "2/22/2013",
        "assignedTo": "Sarah Slegona",
        "priority": "41",
        "sendEmail": "Yes",
        "content": "Buy: Lamination Sheets, Plastic Drawers, File Folders, Ink, and post-its.",
    },
    "To-Do 14": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Order Food from Crisper's",
        "dtDue": "2/23/2013",
        "assignedTo": "Sarah Slegona",
        "priority": "57",
        "sendEmail": "Yes",
        "content": "7 Sandwich platters minimu, assorted varieties. Make sure one is vegetarian.",
    },
    "To-Do 15": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Call Students to Schedule Work",
        "dtDue": "2/22/2013",
        "assignedTo": "James Makowski",
        "priority": "91",
        "sendEmail": "Yes",
        "content": "43 Students required to work the event.",
    },
    "To-Do 16": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Prepare Student Emails",
        "dtDue": "2/22/2013",
        "assignedTo": "Sarah Slegona",
        "priority": "81",
        "sendEmail": "Yes",
        "content": "Prepare student work emails and setup/strike emails.",
    },
    "To-Do 17": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Send Student Emails",
        "dtDue": "2/22/2013",
        "assignedTo": "Sarah Slegona",
        "priority": "81",
        "sendEmail": "Yes",
        "content": "Send emails at 7PM on Friday.",
    },
    "To-Do 18": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Email Executive Committee",
        "dtDue": "2/23/2013",
        "assignedTo": "James Makowski",
        "priority": "94",
        "sendEmail": "Yes",
        "content": "Email weather and numbers to Executive Committee.",
    },
    "To-Do 19": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Deliver Rain Ponchos",
        "dtDue": "2/24/2013",
        "assignedTo": "Sarah Slegona",
        "priority": "2",
        "sendEmail": "Yes",
        "content": "Drop 11 Bins of Rain Ponchos.",
    },
    "To-Do 20": {
        "firstName": "Garrett",
        "lastName": "Moore",
        "toDoName": "Print Master/Bussing/Orientation Schedules",
        "dtDue": "2/23/2013",
        "assignedTo": "Sarah Slegona",
        "priority": "75",
        "sendEmail": "Yes",
        "content": "Make 5 copies of all schedules. Reserve one copy for Sarah Slegona.",
    }
}